services:
  - type: web
    name: qb-webhook
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: QB_REALM
        value: certaincapitaladvisors.quickbase.com
      - key: QB_PARENT_TABLE
        value: buiuyx96s
      - key: QB_DIST_TABLE
        value: buiuypuxi
      - key: QB_USER_TOKEN
        sync: false
      - key: RESEND_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
